LIBCDIR := ../../apps/libc
LIBC_A := $(LIBCDIR)/libc_with_main.a

CC=gcc
LD=ld.lld

CFLAGS = -I. -I$(LIBCDIR) \
		-O2 -Wall -g -m64 -nostdlib -fno-builtin -fno-stack-protector \
		-mcmodel=large -std=c11 \
		-DARCH_MYOS

LDFLAGS = -z norelro --static --image-base=0xffff800000000000

CORE_O=	lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o \
	lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o \
	ltm.o lundump.o lvm.o lzio.o

AUX_O=	lauxlib.o

# LIB_O=	lbaselib.o ldblib.o liolib.o lmathlib.o loslib.o ltablib.o lstrlib.o \
# 	lutf8lib.o loadlib.o lcorolib.o linit.o
LIB_O= lbaselib.o linit.o

LUA_O=	lua.o

ALL_O= $(CORE_O) $(AUX_O) $(LIB_O) $(LUA_O)

TARGET= ../../apps/bin/lua

all: $(TARGET)

$(TARGET): $(ALL_O) $(LIBC_A)
	mkdir -p $(dir $@)
	$(LD) $(ALL_O) $(LIBC_A) -o $@ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBC_A):
	$(MAKE) -C $(LIBCDIR) app

clean:
	rm -f $(ALL_O) $(TARGET)

.PHONY: all clean
